### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by berberman** [fcitx5-android/fcitx5-android#2]
### Outdated, see more on our Trello: https://trello.com/b/gftk6ZdV/kanban

<details>
<summary>Original, outdated Roadmap</summary>

## Short Term

- [x] chinese-addons user dictionary manager UI
- [ ] chinese-addons custom 双拼 profile editor ( https://github.com/fcitx/libime/blob/1.0.11/test/testshuangpinprofile.cpp )
- [x] map Android [`EditorInfo`](https://developer.android.com/reference/android/view/inputmethod/EditorInfo) (and [`InputType`](https://developer.android.com/reference/android/text/InputType)) to fcitx5 [`CapabilityFlag`](https://github.com/fcitx/fcitx5/blob/5.0.13/src/lib/fcitx-utils/capabilityflags.h)
#23 
- [ ] share input state per program (maybe create an input context for each application)
- [ ] surrounding text support in `androidkeyboard` (Android: [`InputConnection#getSurroundingText`](https://developer.android.com/reference/android/view/inputmethod/InputConnection#getSurroundingText(int,%20int,%20int)); fcitx5: [`fcitx::SurroundingText`](https://github.com/fcitx/fcitx5/blob/5.0.13/src/lib/fcitx/surroundingtext.h))
- [x] invokeAction support in `androidkeyboard` (reference: [`PinyinEngine::invokeActionImpl`](https://github.com/fcitx/fcitx5-chinese-addons/blob/5.0.10/im/pinyin/pinyin.cpp#L1763))
https://github.com/rocka/fcitx5-android-poc/commit/e2ffe7e950262ac692ecc5730e01f4e055809cdc
- [ ] new fcitx API to now whether next "Return" `KeyEvent` would be captrued

## Mid Term

- [x] [`fcitx5-lua`](https://github.com/fcitx/fcitx5-lua)
#31

## Long Term

- [ ] fully customizable keyboard layout
- [ ] [`fcitx5-mozc`](https://github.com/fcitx/mozc)

## Nice to have
- [ ] Support Direct Boot mode (https://developer.android.com/training/articles/direct-boot)

</details>

**Comment by wengxt** [comment]
……你确定配置双拼方案要放手机端做  ´_>`……

**Comment by wengxt** [comment]
当然，不是说不行，其实只需要一个中介转换成 fcitx::Configuration，不用单独写界面，桌面都可以用，就像现在的自定义标点的配置界面一样……只是这个并不特别重要。

重要的还是正规的虚拟键盘接口，怎么组织虚拟键盘和桌面输入法的关系

**Comment by zenfas** [comment]
Can you support glide typing like Gboard or Switfkey in future
